### PR TITLE
v7.4.0

### PR DESCRIPTION
**Pull request by designsaves**

### CODE REVIEW

**Comment by designsaves** [comment]
Merges in the following PRs:
https://github.com/andyet/yeti.css/pull/117
https://github.com/andyet/yeti.css/pull/115
https://github.com/andyet/yeti.css/pull/114
https://github.com/andyet/yeti.css/pull/112
https://github.com/andyet/yeti.css/pull/111
https://github.com/andyet/yeti.css/pull/109
https://github.com/andyet/yeti.css/pull/108

**Comment by designsaves** [comment]
# **Proposed release notes:**

## CSS

### Navigation
- Navigation dropdown width fix (https://github.com/andyet/yeti.css/pull/115)

### Grid
- Add .grid-flex-cell-centered to the grid system. (https://github.com/andyet/yeti.css/pull/114)

### Buttons
- Enable all button variations to work in button-group (https://github.com/andyet/yeti.css/pull/112)
- Small button padding (https://github.com/andyet/yeti.css/pull/109)

## Documentation
- Update grid information to reflect changes
- Update button information to reflect changes
- Update the button examples in the docs to all be `button` elements rather than `a` tags for consistency - with the exception of one example which is specifically called out
- Fix approval button typo (https://github.com/andyet/yeti.css/pull/108)

## Misc
- Ignore .DS_Store files (https://github.com/andyet/yeti.css/pull/117)
- Update dependencies (https://github.com/andyet/yeti.css/pull/111)

**Review by lynnandtonic — APPROVED** [review]
Nice, Terry! One thought I had was that it might be good to explicitly say in the documentation that you might use the `.button` classes on `<button>` and `<a>` elements? I know you can figure this out by looking through the CSS, but might be good to be clear about it since it's a common use case.

Besides that, LGTM!

**Comment by katefarrar** [comment]
Looks awesome.  The release notes are 👌👌 

I second @lynnandtonic's comment about the `button` class.

One thing I noticed - should we update the footer to say `“from your friends at &yet”` instead of `"Designed and built by @ fox."` ?

**Review by katefarrar — APPROVED** [review]

**Comment by designsaves** [comment]
@katefarrar I think we should keep the attribution as is.

**Pull request merged**
