### PR TITLE
Add yarn.lock for yarn install

### PR DESCRIPTION
**Pull request by arturoromeroslc**
NPM to [yarn](https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/) support for faster install times.

### CODE REVIEW

**Comment by latentflip** [comment]
Hey @arturoromeroslc is there a reason that we need this if we aren't using yarn to develop yeti.css?

**Comment by arturoromeroslc** [comment]
@latentflip it would primarily add increased install time for devs using yarn as a package manager instead of npm. 

From the get-go, the Yarn lockfile guarantees that repeatedly running yarn on the same repository results in the same packages.  

[yarn.com](https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/)
`These lockfiles lock the installed dependencies to a specific version, and ensure that every install results in the exact same file structure in node_modules across all machines` 

Second, Yarn attempts to have good performance, with a cold cache, but especially with a warm cache.

The Yarn today has good performance, but I think it will get even better, adding a lockfile to a repo would insure that a user gets optimal performance when installing yeti using yarn.

**Comment by arturoromeroslc** [comment]
@latentflip If you think this is a direction you would like to go.  I will be glad to update the ReadMe by documenting for yarn (which is not that different from `npm`).

**Comment by latentflip** [comment]
I'm unclear if adding a yarn lockfile will improve things for people with yeticss as a dependency, or only for people developing on yeticss directly?

Either way I'm not sure i see the benefit as it's a file we would have to keep up to date, rather than just relying on semver for yeticss' dependencies.

So at the moment I'm afraid I don't really see a compelling reason to add this I'm afraid, but correct me if I'm wrong.

**Comment by latentflip** [comment]
I think we'll follow this advice for now: https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf#.ovdqnt8t4

**Pull request closed without merging**
