### PR TITLE
add caution button

### PR DESCRIPTION
**Pull request by adamavenir**
I wanted to add a "caution" button style that I tend to prefer for actions like `delete`

Nice to have this for cases where the `button-warn` red button style feels too visually dominating—keeping the red in the text, but removing the background, like so:

### CODE REVIEW

**Comment by designsaves** [comment]
+1

**Comment by adamavenir** [comment]
Should it perhaps also remove the `padding-left` and `padding-right`? I considered it, but I'm not sure.

**Comment by designsaves** [comment]
@adambrault That's a good question. My gut reaction is to keep the padding. I don't know your specific use case, but for what I envision, it would be necessary.

**Comment by adamavenir** [comment]
@meetthelegend works for me in most cases.

**Pull request merged**
